x-depends_on: &default-depends_on
  - postgres
  - redis
x-volumes: &default-volumes
  - .:/code
services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - /tmp/glitchtip-postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
  redis:
    image: valkey/valkey:8
  web:
    # Uncomment for breakpoint
    #stdin_open: true
    #tty: true
    build: .
    user: root # Allows for usage of ipdb, apt, etc in dev
    command: ./manage.py runserver 0.0.0.0:8000
    #command: python app.py
    #command: python -m gunicorn glitchtip.asgi:application -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0
    depends_on: *default-depends_on
    volumes: *default-volumes
    ports:
      - "8000:8000"
    env_file:
      - .env
  worker:
    build: .
    user: root
    command: bin/run-celery-with-beat.sh
    depends_on: *default-depends_on
    volumes: *default-volumes
    env_file:
      - .env
