# Generated by Django 5.2.4 on 2025-08-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_events', '0004_auto_20250626_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='ai_analysis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
